apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deployment
  labels:
    app: voting-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-pod
  template:
    metadata:
      name: voting-pod
      labels:
        app: voting-pod
    spec:
      containers:
        - name: voting-app
          image: kodekloud/examplevotingapp_vote_vote:v1
          ports:
            - containerPort: 80
          env:
            - name: OPTION_A
              value: "Cats"
            - name: OPTION_B
              value: "Dogs"
        - name: redis
          image: redis:alpine
        - name: postgres
          image: postgres:9.4
        - name: worker
          image: kodekloud/examplevotingapp_worker:v1
        - name: result-app
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80
          env:
            - name: OPTION_C
              value: "Snakes"
